### ISSUE TITLE
Incompatible with Ember CLI 3.7.x

### ISSUE THREAD

**Issue by Turbo87** [workmanw/ember-qunit-assert-helpers#26]
https://github.com/ember-cli/ember-cli/pull/8264 removed the private `_requireBuildPackages()` method on the `Addon` class that this project is calling. To fix it in a backward-compatible way we should probably check if the method exists before trying to call it.

**Comment by toranb** [comment]
Confirm -just found this myself today :)

**Comment by Turbo87** [comment]
@workmanw do you have time to release this in the next days?

**Comment by workmanw** [comment]
@Turbo87 Yeap, I'll get it done today.

**Comment by Turbo87** [comment]
awesome, thank you very much! 🙏

**Comment by workmanw** [comment]
@Turbo87 Sorry for the delay. I just published v0.2.2. Thanks for the nudge :)
